[package]
name = "skeletrust"
version = "0.1.0"
edition = "2021"

# Skeletor is a rust project scaffold
#
# last updated 12/28/2022

[dependencies]
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["full"] }# use only for async development

[dev-dependencies]
anyhow = "1.0.68"
